fix: Remove incorrect fields from gatekeeper test (#1090)
Fixes: #1089

Looks like there was a change in gatekeeper deployment manifests that causes e2e tests to fail with the below message:

```
STEP: kubectl apply --kubeconfig=/agent/_work/1/s/_output/aad-pod-identity-e2e-70b6/kubeconfig/kubeconfig.westus2.json --namespace=gatekeeper-9wnsd -f /tmp/470855604
error: error validating "/tmp/470855604": error validating data: [ValidationError(ConstraintTemplate.spec.crd.spec.names): unknown field "listKind" in sh.gatekeeper.templates.v1beta1.ConstraintTemplate.spec.crd.spec.names, ValidationError(ConstraintTemplate.spec.crd.spec.names): unknown field "plural" in sh.gatekeeper.templates.v1beta1.ConstraintTemplate.spec.crd.spec.names, ValidationError(ConstraintTemplate.spec.crd.spec.names): unknown field "singular" in sh.gatekeeper.templates.v1beta1.ConstraintTemplate.spec.crd.spec.names]; if you choose to ignore these errors, turn validation off with --validate=false
```

This looks to be caused by Gatekeeper updating their CRDs recently in master that no longer allows additional invalid fields to be passed in the CRD spec since promoting to `apiextensions.k8s.io/v1`. The e2e tests looks to take the latest gatekeeper deployment manifests from master, hence the breaking change.